{"stackTrace": [["/var/task/lambda.py", 10, "lambda_handler", "ec2.start_instances(InstanceIds=instances)"], ["/var/runtime/botocore/client.py", 314, "_api_call", "return self._make_api_call(operation_name, kwargs)"], ["/var/runtime/botocore/client.py", 612, "_make_api_call", "raise error_class(parsed_response, operation_name)"]], "errorType": "ClientError", "errorMessage": "An error occurred (UnauthorizedOperation) when calling the StartInstances operation: You are not authorized to perform this operation. Encoded authorization failure message: s19rTPQFhCy9k38DC92ZwXumkoxL0mOCtBuZ92tJNBYLtLQ4D7AX87qoW5k22PL9dfrZ65vyuneBk5vprw_Q-pcFlqLI_HFkljClp8nSwMO5AiBUDSWAIe6rQd7ZHyf4juT61hW2V2FUNbqC_n5RYENuBhN510UTfh7ScCC_n9e74I86lBBW2AkZEsiQYsIllqjzJ1y9Vzka658YNwMBd5u3Hv2BpM9JpNcFSrKcwpsGVtZ28FZaDcgvK7Nfh7PpGTHKOBceU896xlvmLIm9iNHQ_jZ5l5fBpRm4oOqJmFUB1UuCK3FlT3xPzOepRUDRqfoF7Gt7t-KDluj34ivSSmpogOk8JHv5h6Ksr4TXVNhlLUniFjvy83oF_jH_rOOSdL2u9cJuiSpSvRfOmW08G1tj4pqeK-2Q4-slmKsFC1jqxdJHrRwKu-oQNupfGKXMt_vpArg4G63E-dENg_wRsQnrVh1oEsHRRd2lDsfETB6XXO9kSE1q5vyPvE1acgCtWmaRgyWknHLpOhza-_LDHYU5_g6KrgbsvU1ufWcOx7g89_mq0E-Qw4fRXNYpJ6GD0zySjWIVxTWG7gqyxWF2srRNI4OYBv7OICSk1GQPDmYKn-A3a2nsuwKJ07SLxWQcqzzHEyAWeMXuK0wz9XIfOqstcAhgz7GIok1gK99nzBfEgiHceykRjZNPRgVRMp8NleZptxckYch-q_fNeBI4x8NTf2vypkUYddmlTw-IVtjzSMG2wBLw9OdiN0UjtVsWVPM4MKw8hvZShBhYV210K5D4H1u8kx1MJOZKY-jGNk6Z4Tm8xltMhib-eCjvZtnfnuPSZX5hEvt_kN07eS3RIa7c4on903RUfD7ZxIaBPfrDTWbi20RUoqDJbiU"}